// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package celldb

import (
	"time"
)

type AppUser struct {
	ID           string
	HomeTenantID string
	IdpIssuer    string
	IdpSubject   string
	Email        *string
	CreatedAt    time.Time
}

type OrgMember struct {
	TenantID  string
	UserID    string
	Role      string
	CreatedAt time.Time
}

type OrgSetting struct {
	TenantID                   string
	MembersCanCreateWorkspaces bool
	UpdatedAt                  time.Time
}

type Session struct {
	ID              string
	WorkspaceID     string
	TenantID        string
	UserID          string
	IdleTimeoutSecs *int32
	CreatedAt       time.Time
}

type Workspace struct {
	ID               string
	TenantID         string
	Name             string
	OwnerUserID      string
	AccessScope      string
	NextUid          int32
	Generation       int64
	TaskRef          *string
	Status           string
	LastError        *string
	IdleTimeoutSecs  int32
	WarmHoldSecs     int32
	WarmHoldUntil    *time.Time
	SnapshotID       *string
	IdlePinnedSince  *time.Time
	AdmissionPolicy  string
	MaxSessions      int32
	MinFreeMemoryPct int32
	CreatedAt        time.Time
}

type WorkspaceMember struct {
	WorkspaceID string
	UserID      string
	TenantID    string
	Role        string
	Uid         *int32
	CreatedAt   time.Time
}
