// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package celldb

import (
	"context"
	"time"
)

const addMember = `-- name: AddMember :one
INSERT INTO workspace_member (workspace_id, user_id, tenant_id, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, user_id) DO UPDATE SET role = excluded.role
RETURNING workspace_id, user_id, tenant_id, role, uid, created_at
`

type AddMemberParams struct {
	WorkspaceID string
	UserID      string
	TenantID    string
	Role        string
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, addMember,
		arg.WorkspaceID,
		arg.UserID,
		arg.TenantID,
		arg.Role,
	)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.TenantID,
		&i.Role,
		&i.Uid,
		&i.CreatedAt,
	)
	return i, err
}

const addOrgMember = `-- name: AddOrgMember :one
INSERT INTO org_member (tenant_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, user_id) DO UPDATE SET role = excluded.role
RETURNING tenant_id, user_id, role, created_at
`

type AddOrgMemberParams struct {
	TenantID string
	UserID   string
	Role     string
}

func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, addOrgMember, arg.TenantID, arg.UserID, arg.Role)
	var i OrgMember
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO session (id, workspace_id, tenant_id, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, tenant_id, user_id, idle_timeout_secs, created_at
`

type CreateSessionParams struct {
	ID          string
	WorkspaceID string
	TenantID    string
	UserID      string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.WorkspaceID,
		arg.TenantID,
		arg.UserID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TenantID,
		&i.UserID,
		&i.IdleTimeoutSecs,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO app_user (id, home_tenant_id, idp_issuer, idp_subject, email)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, home_tenant_id, idp_issuer, idp_subject, email, created_at
`

type CreateUserParams struct {
	ID           string
	HomeTenantID string
	IdpIssuer    string
	IdpSubject   string
	Email        *string
}

// Every query carries an explicit tenant_id predicate even though RLS enforces
// the same thing. See schema.sql: the policy makes it true, the predicate makes
// it visible to whoever reads the call site.
//
// app_user is the exception, and only because it HAS no tenant_id -- a user
// belongs to the cell and to many organizations. Its queries therefore lean on
// the policy alone, which is worth noticing rather than skimming past: these
// are the only reads in this file where nothing at the call site says what
// limits them.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.HomeTenantID,
		arg.IdpIssuer,
		arg.IdpSubject,
		arg.Email,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.HomeTenantID,
		&i.IdpIssuer,
		&i.IdpSubject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspace (id, tenant_id, name, owner_user_id, access_scope)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, owner_user_id, access_scope, next_uid, generation, task_ref, status, last_error, idle_timeout_secs, warm_hold_secs, warm_hold_until, snapshot_id, idle_pinned_since, admission_policy, max_sessions, min_free_memory_pct, created_at
`

type CreateWorkspaceParams struct {
	ID          string
	TenantID    string
	Name        string
	OwnerUserID string
	AccessScope string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.OwnerUserID,
		arg.AccessScope,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OwnerUserID,
		&i.AccessScope,
		&i.NextUid,
		&i.Generation,
		&i.TaskRef,
		&i.Status,
		&i.LastError,
		&i.IdleTimeoutSecs,
		&i.WarmHoldSecs,
		&i.WarmHoldUntil,
		&i.SnapshotID,
		&i.IdlePinnedSince,
		&i.AdmissionPolicy,
		&i.MaxSessions,
		&i.MinFreeMemoryPct,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM session WHERE id = $1 AND tenant_id = $2
`

type DeleteSessionParams struct {
	ID       string
	TenantID string
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWorkspace = `-- name: DeleteWorkspace :execrows
DELETE FROM workspace WHERE id = $1 AND tenant_id = $2
`

type DeleteWorkspaceParams struct {
	ID       string
	TenantID string
}

func (q *Queries) DeleteWorkspace(ctx context.Context, arg DeleteWorkspaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspace, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureMember = `-- name: EnsureMember :exec
INSERT INTO workspace_member (workspace_id, user_id, tenant_id, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, user_id) DO NOTHING
`

type EnsureMemberParams struct {
	WorkspaceID string
	UserID      string
	TenantID    string
	Role        string
}

// Ensure a membership row exists without touching an existing role.
//
// DO NOTHING rather than AddMember's DO UPDATE, and the difference is the whole
// reason this exists separately: a workspace open to the whole organization has
// no rows until somebody starts a session, and creating one on the way past must
// not be able to demote the workspace's owner to 'user'. Same reasoning as
// JoinOrg above.
func (q *Queries) EnsureMember(ctx context.Context, arg EnsureMemberParams) error {
	_, err := q.db.Exec(ctx, ensureMember,
		arg.WorkspaceID,
		arg.UserID,
		arg.TenantID,
		arg.Role,
	)
	return err
}

const failWorkspacePlacement = `-- name: FailWorkspacePlacement :exec
UPDATE workspace SET status = $3, task_ref = $4, last_error = $5
WHERE id = $1 AND tenant_id = $2
`

type FailWorkspacePlacementParams struct {
	ID        string
	TenantID  string
	Status    string
	TaskRef   *string
	LastError *string
}

// The other half: a placement that failed, recorded where the console and the
// next caller can both read it. One statement with the status, so a row can
// never say `stopped` with no reason or carry a reason while claiming to be on
// its way up.
//
// The STATUS is the caller's to choose, and the choice is "may a task exist".
// Nothing was placed before dispatch, so that is `stopped`; a task that was
// dispatched and never dialed in may well be out there, so that stays
// `starting` with its reference -- which is also what earns it the reconnect
// grace on the next attempt instead of a second task (see ensureWorkspace).
func (q *Queries) FailWorkspacePlacement(ctx context.Context, arg FailWorkspacePlacementParams) error {
	_, err := q.db.Exec(ctx, failWorkspacePlacement,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.TaskRef,
		arg.LastError,
	)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT workspace_id, user_id, tenant_id, role, uid, created_at FROM workspace_member WHERE workspace_id = $1 AND user_id = $2 AND tenant_id = $3
`

type GetMembershipParams struct {
	WorkspaceID string
	UserID      string
	TenantID    string
}

// The authorisation primitive: what, if anything, is this user to this
// workspace. Absent means no access at all.
func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.WorkspaceID, arg.UserID, arg.TenantID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.TenantID,
		&i.Role,
		&i.Uid,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgMembership = `-- name: GetOrgMembership :one
SELECT tenant_id, user_id, role, created_at FROM org_member WHERE tenant_id = $1 AND user_id = $2
`

type GetOrgMembershipParams struct {
	TenantID string
	UserID   string
}

// The authorisation primitive for an organization: what, if anything, is this
// user to it. Absent means no access, and the caller answers 404 rather than
// 403 -- whether an organization exists is not a stranger's business.
func (q *Queries) GetOrgMembership(ctx context.Context, arg GetOrgMembershipParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, getOrgMembership, arg.TenantID, arg.UserID)
	var i OrgMember
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgSettings = `-- name: GetOrgSettings :one
SELECT tenant_id, members_can_create_workspaces, updated_at FROM org_settings WHERE tenant_id = $1
`

// Organization settings. No row means defaults, so callers treat ErrNotFound as
// an answer rather than a failure (see Server.orgSettings).
func (q *Queries) GetOrgSettings(ctx context.Context, tenantID string) (OrgSetting, error) {
	row := q.db.QueryRow(ctx, getOrgSettings, tenantID)
	var i OrgSetting
	err := row.Scan(&i.TenantID, &i.MembersCanCreateWorkspaces, &i.UpdatedAt)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, workspace_id, tenant_id, user_id, idle_timeout_secs, created_at FROM session WHERE id = $1 AND tenant_id = $2
`

type GetSessionParams struct {
	ID       string
	TenantID string
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, arg.ID, arg.TenantID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TenantID,
		&i.UserID,
		&i.IdleTimeoutSecs,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, home_tenant_id, idp_issuer, idp_subject, email, created_at FROM app_user WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.HomeTenantID,
		&i.IdpIssuer,
		&i.IdpSubject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserBySubject = `-- name: GetUserBySubject :one
SELECT id, home_tenant_id, idp_issuer, idp_subject, email, created_at FROM app_user WHERE idp_issuer = $1 AND idp_subject = $2
`

type GetUserBySubjectParams struct {
	IdpIssuer  string
	IdpSubject string
}

func (q *Queries) GetUserBySubject(ctx context.Context, arg GetUserBySubjectParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserBySubject, arg.IdpIssuer, arg.IdpSubject)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.HomeTenantID,
		&i.IdpIssuer,
		&i.IdpSubject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, tenant_id, name, owner_user_id, access_scope, next_uid, generation, task_ref, status, last_error, idle_timeout_secs, warm_hold_secs, warm_hold_until, snapshot_id, idle_pinned_since, admission_policy, max_sessions, min_free_memory_pct, created_at FROM workspace WHERE id = $1 AND tenant_id = $2
`

type GetWorkspaceParams struct {
	ID       string
	TenantID string
}

func (q *Queries) GetWorkspace(ctx context.Context, arg GetWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, arg.ID, arg.TenantID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OwnerUserID,
		&i.AccessScope,
		&i.NextUid,
		&i.Generation,
		&i.TaskRef,
		&i.Status,
		&i.LastError,
		&i.IdleTimeoutSecs,
		&i.WarmHoldSecs,
		&i.WarmHoldUntil,
		&i.SnapshotID,
		&i.IdlePinnedSince,
		&i.AdmissionPolicy,
		&i.MaxSessions,
		&i.MinFreeMemoryPct,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceByName = `-- name: GetWorkspaceByName :one
SELECT id, tenant_id, name, owner_user_id, access_scope, next_uid, generation, task_ref, status, last_error, idle_timeout_secs, warm_hold_secs, warm_hold_until, snapshot_id, idle_pinned_since, admission_policy, max_sessions, min_free_memory_pct, created_at FROM workspace WHERE name = $1 AND tenant_id = $2
`

type GetWorkspaceByNameParams struct {
	Name     string
	TenantID string
}

func (q *Queries) GetWorkspaceByName(ctx context.Context, arg GetWorkspaceByNameParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByName, arg.Name, arg.TenantID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OwnerUserID,
		&i.AccessScope,
		&i.NextUid,
		&i.Generation,
		&i.TaskRef,
		&i.Status,
		&i.LastError,
		&i.IdleTimeoutSecs,
		&i.WarmHoldSecs,
		&i.WarmHoldUntil,
		&i.SnapshotID,
		&i.IdlePinnedSince,
		&i.AdmissionPolicy,
		&i.MaxSessions,
		&i.MinFreeMemoryPct,
		&i.CreatedAt,
	)
	return i, err
}

const joinOrg = `-- name: JoinOrg :execrows
INSERT INTO org_member (tenant_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, user_id) DO NOTHING
`

type JoinOrgParams struct {
	TenantID string
	UserID   string
	Role     string
}

// Redemption must not quietly demote someone who is already an owner, so it
// does NOT overwrite an existing role -- unlike AddOrgMember, which is an
// administrative act by someone who meant it.
func (q *Queries) JoinOrg(ctx context.Context, arg JoinOrgParams) (int64, error) {
	result, err := q.db.Exec(ctx, joinOrg, arg.TenantID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.workspace_id, m.user_id, m.tenant_id, m.role, m.uid, m.created_at, u.email
FROM workspace_member m
         JOIN app_user u ON u.id = m.user_id
WHERE m.workspace_id = $1
  AND m.tenant_id = $2
ORDER BY m.created_at
`

type ListMembersParams struct {
	WorkspaceID string
	TenantID    string
}

type ListMembersRow struct {
	WorkspaceID string
	UserID      string
	TenantID    string
	Role        string
	Uid         *int32
	CreatedAt   time.Time
	Email       *string
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, arg.WorkspaceID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.TenantID,
			&i.Role,
			&i.Uid,
			&i.CreatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT u.id, u.home_tenant_id, u.idp_issuer, u.idp_subject, u.email, u.created_at, m.role
FROM org_member m
         JOIN app_user u ON u.id = m.user_id
WHERE m.tenant_id = $1
ORDER BY u.created_at
`

type ListOrgMembersRow struct {
	ID           string
	HomeTenantID string
	IdpIssuer    string
	IdpSubject   string
	Email        *string
	CreatedAt    time.Time
	Role         string
}

// Everyone in one organization, for the owner columns the console renders.
// Through org_member rather than over app_user, so the tenant predicate is
// expressible here like everywhere else.
func (q *Queries) ListOrgMembers(ctx context.Context, tenantID string) ([]ListOrgMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgMembersRow{}
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeTenantID,
			&i.IdpIssuer,
			&i.IdpSubject,
			&i.Email,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgSessions = `-- name: ListOrgSessions :many
SELECT id, workspace_id, tenant_id, user_id, idle_timeout_secs, created_at FROM session WHERE tenant_id = $1 ORDER BY created_at DESC
`

// Every session in the organization, for an organization owner.
func (q *Queries) ListOrgSessions(ctx context.Context, tenantID string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listOrgSessions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TenantID,
			&i.UserID,
			&i.IdleTimeoutSecs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgSessionsVisible = `-- name: ListOrgSessionsVisible :many
SELECT s.id, s.workspace_id, s.tenant_id, s.user_id, s.idle_timeout_secs, s.created_at
FROM session s
WHERE s.tenant_id = $1
  AND (s.user_id = $2
    OR EXISTS (SELECT 1
               FROM workspace_member m
               WHERE m.workspace_id = s.workspace_id
                 AND m.user_id = $2
                 AND m.tenant_id = $1
                 AND m.role = 'owner'))
ORDER BY s.created_at DESC
`

type ListOrgSessionsVisibleParams struct {
	TenantID string
	UserID   string
}

// What everyone else may see across the whole organization: their own sessions,
// plus every session in a workspace they own. The same rule ListSessions and
// ListSessionsForUser split per workspace, expressed once for all of them --
// which is what `lem --session <id>` needs, since it resolves a prefix without
// being told a workspace.
func (q *Queries) ListOrgSessionsVisible(ctx context.Context, arg ListOrgSessionsVisibleParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listOrgSessionsVisible, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TenantID,
			&i.UserID,
			&i.IdleTimeoutSecs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsForUser = `-- name: ListOrgsForUser :many
SELECT tenant_id, user_id, role, created_at FROM org_member WHERE user_id = $1 ORDER BY created_at
`

// Which organizations am I in. The one query that is deliberately NOT scoped to
// a single organization, and the reason org_member's policy also admits rows by
// user_id -- see schema.sql.
func (q *Queries) ListOrgsForUser(ctx context.Context, userID string) ([]OrgMember, error) {
	rows, err := q.db.Query(ctx, listOrgsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgMember{}
	for rows.Next() {
		var i OrgMember
		if err := rows.Scan(
			&i.TenantID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, workspace_id, tenant_id, user_id, idle_timeout_secs, created_at FROM session WHERE workspace_id = $1 AND tenant_id = $2 ORDER BY created_at DESC
`

type ListSessionsParams struct {
	WorkspaceID string
	TenantID    string
}

// What a workspace OWNER sees: every session in it, whoever started them.
func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, arg.WorkspaceID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TenantID,
			&i.UserID,
			&i.IdleTimeoutSecs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForUser = `-- name: ListSessionsForUser :many
SELECT id, workspace_id, tenant_id, user_id, idle_timeout_secs, created_at FROM session
WHERE workspace_id = $1 AND tenant_id = $2 AND user_id = $3
ORDER BY created_at DESC
`

type ListSessionsForUserParams struct {
	WorkspaceID string
	TenantID    string
	UserID      string
}

// What a plain member sees: only their own. Two named queries rather than one
// query with a conditional, because the conditional is the part worth being
// able to read -- and each is independently testable.
func (q *Queries) ListSessionsForUser(ctx context.Context, arg ListSessionsForUserParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsForUser, arg.WorkspaceID, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TenantID,
			&i.UserID,
			&i.IdleTimeoutSecs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, tenant_id, name, owner_user_id, access_scope, next_uid, generation, task_ref, status, last_error, idle_timeout_secs, warm_hold_secs, warm_hold_until, snapshot_id, idle_pinned_since, admission_policy, max_sessions, min_free_memory_pct, created_at FROM workspace WHERE tenant_id = $1 ORDER BY name
`

// Admin view: everything in the tenant.
func (q *Queries) ListWorkspaces(ctx context.Context, tenantID string) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspaces, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.OwnerUserID,
			&i.AccessScope,
			&i.NextUid,
			&i.Generation,
			&i.TaskRef,
			&i.Status,
			&i.LastError,
			&i.IdleTimeoutSecs,
			&i.WarmHoldSecs,
			&i.WarmHoldUntil,
			&i.SnapshotID,
			&i.IdlePinnedSince,
			&i.AdmissionPolicy,
			&i.MaxSessions,
			&i.MinFreeMemoryPct,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.tenant_id, w.name, w.owner_user_id, w.access_scope, w.next_uid, w.generation, w.task_ref, w.status, w.last_error, w.idle_timeout_secs, w.warm_hold_secs, w.warm_hold_until, w.snapshot_id, w.idle_pinned_since, w.admission_policy, w.max_sessions, w.min_free_memory_pct, w.created_at
FROM workspace w
WHERE w.tenant_id = $1
  AND (w.access_scope = 'org'
    OR EXISTS (SELECT 1
               FROM workspace_member m
               WHERE m.workspace_id = w.id
                 AND m.user_id = $2))
ORDER BY w.name
`

type ListWorkspacesForUserParams struct {
	TenantID string
	UserID   string
}

// What a non-admin may see: workspaces open to the whole organization, plus the
// ones they own or were added to. Creating a workspace also writes an owner
// membership row, so the creator's own arrives through the same route -- one
// rule instead of a special case.
//
// EXISTS rather than the JOIN this replaced, and that is not a stylistic
// preference: with the org disjunct added, a JOIN returns a workspace TWICE for
// a user who is both an explicit member and covered by access_scope = 'org'.
// EXISTS cannot duplicate a row. It also matches how app_user's RLS policy asks
// the same question, so there is one shape for "is this person a member".
func (q *Queries) ListWorkspacesForUser(ctx context.Context, arg ListWorkspacesForUserParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.OwnerUserID,
			&i.AccessScope,
			&i.NextUid,
			&i.Generation,
			&i.TaskRef,
			&i.Status,
			&i.LastError,
			&i.IdleTimeoutSecs,
			&i.WarmHoldSecs,
			&i.WarmHoldUntil,
			&i.SnapshotID,
			&i.IdlePinnedSince,
			&i.AdmissionPolicy,
			&i.MaxSessions,
			&i.MinFreeMemoryPct,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextGeneration = `-- name: NextGeneration :one
UPDATE workspace SET generation = generation + 1
WHERE id = $1 AND tenant_id = $2
RETURNING generation
`

type NextGenerationParams struct {
	ID       string
	TenantID string
}

// Atomic. The previous JSON store read the record, incremented, and wrote back
// a copy taken BEFORE the increment, so the counter never left zero and two
// genuinely different placements derived the same ECS client-token -- which ECS
// answers with the original task (section 2.8). A single UPDATE ... RETURNING
// cannot express that bug.
func (q *Queries) NextGeneration(ctx context.Context, arg NextGenerationParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextGeneration, arg.ID, arg.TenantID)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const nextWorkspaceUID = `-- name: NextWorkspaceUID :one
UPDATE workspace SET next_uid = next_uid + 1
WHERE id = $1 AND tenant_id = $2
RETURNING next_uid - 1
`

type NextWorkspaceUIDParams struct {
	ID       string
	TenantID string
}

// Take the next POSIX uid for this workspace, atomically.
//
// Reads like NextGeneration and for the same reason: a read-modify-write here
// would let two concurrent first-sessions take the same number, and the thing
// the number keeps apart is one member's home from another's.
//
// The counter only ever climbs, so a departed member's uid is never handed out
// again -- their files are still on the volume under it.
func (q *Queries) NextWorkspaceUID(ctx context.Context, arg NextWorkspaceUIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextWorkspaceUID, arg.ID, arg.TenantID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const removeMember = `-- name: RemoveMember :execrows
DELETE FROM workspace_member WHERE workspace_id = $1 AND user_id = $2 AND tenant_id = $3
`

type RemoveMemberParams struct {
	WorkspaceID string
	UserID      string
	TenantID    string
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMember, arg.WorkspaceID, arg.UserID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeOrgMember = `-- name: RemoveOrgMember :execrows
DELETE FROM org_member WHERE tenant_id = $1 AND user_id = $2
`

type RemoveOrgMemberParams struct {
	TenantID string
	UserID   string
}

func (q *Queries) RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeOrgMember, arg.TenantID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameWorkspace = `-- name: RenameWorkspace :one
UPDATE workspace SET name = $3 WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, owner_user_id, access_scope, next_uid, generation, task_ref, status, last_error, idle_timeout_secs, warm_hold_secs, warm_hold_until, snapshot_id, idle_pinned_since, admission_policy, max_sessions, min_free_memory_pct, created_at
`

type RenameWorkspaceParams struct {
	ID       string
	TenantID string
	Name     string
}

// Rename, which is the reason id and name are separate columns at all. Refused
// by the caller while a task is live: everything OUTSIDE the database is keyed
// on the name, so renaming under a running task orphans its tunnel and
// invalidates the credential it is holding.
func (q *Queries) RenameWorkspace(ctx context.Context, arg RenameWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, renameWorkspace, arg.ID, arg.TenantID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OwnerUserID,
		&i.AccessScope,
		&i.NextUid,
		&i.Generation,
		&i.TaskRef,
		&i.Status,
		&i.LastError,
		&i.IdleTimeoutSecs,
		&i.WarmHoldSecs,
		&i.WarmHoldUntil,
		&i.SnapshotID,
		&i.IdlePinnedSince,
		&i.AdmissionPolicy,
		&i.MaxSessions,
		&i.MinFreeMemoryPct,
		&i.CreatedAt,
	)
	return i, err
}

const setIdlePinned = `-- name: SetIdlePinned :exec
UPDATE workspace SET idle_pinned_since = $3 WHERE id = $1 AND tenant_id = $2
`

type SetIdlePinnedParams struct {
	ID              string
	TenantID        string
	IdlePinnedSince *time.Time
}

// Section 2.4: this workspace would be stopping, and the only thing holding it
// open is a background process inside a session. Recorded so the console can
// say so; nothing acts on it, because the member who started that process meant
// to, and stopping the session would kill it.
func (q *Queries) SetIdlePinned(ctx context.Context, arg SetIdlePinnedParams) error {
	_, err := q.db.Exec(ctx, setIdlePinned, arg.ID, arg.TenantID, arg.IdlePinnedSince)
	return err
}

const setMemberUID = `-- name: SetMemberUID :one
UPDATE workspace_member SET uid = $4
WHERE workspace_id = $1 AND user_id = $2 AND tenant_id = $3 AND uid IS NULL
RETURNING workspace_id, user_id, tenant_id, role, uid, created_at
`

type SetMemberUIDParams struct {
	WorkspaceID string
	UserID      string
	TenantID    string
	Uid         *int32
}

// Assign a uid to a member who has none.
//
// `AND uid IS NULL` is what makes it safe to call on every session: somebody who
// already has one is not renumbered, and a caller that lost the race gets no
// rows rather than overwriting the winner.
func (q *Queries) SetMemberUID(ctx context.Context, arg SetMemberUIDParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, setMemberUID,
		arg.WorkspaceID,
		arg.UserID,
		arg.TenantID,
		arg.Uid,
	)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.TenantID,
		&i.Role,
		&i.Uid,
		&i.CreatedAt,
	)
	return i, err
}

const setOrgRole = `-- name: SetOrgRole :execrows
UPDATE org_member SET role = $3 WHERE tenant_id = $1 AND user_id = $2
`

type SetOrgRoleParams struct {
	TenantID string
	UserID   string
	Role     string
}

func (q *Queries) SetOrgRole(ctx context.Context, arg SetOrgRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOrgRole, arg.TenantID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSessionIdleTimeout = `-- name: SetSessionIdleTimeout :one
UPDATE session SET idle_timeout_secs = $3 WHERE id = $1 AND tenant_id = $2
RETURNING id, workspace_id, tenant_id, user_id, idle_timeout_secs, created_at
`

type SetSessionIdleTimeoutParams struct {
	ID              string
	TenantID        string
	IdleTimeoutSecs *int32
}

func (q *Queries) SetSessionIdleTimeout(ctx context.Context, arg SetSessionIdleTimeoutParams) (Session, error) {
	row := q.db.QueryRow(ctx, setSessionIdleTimeout, arg.ID, arg.TenantID, arg.IdleTimeoutSecs)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TenantID,
		&i.UserID,
		&i.IdleTimeoutSecs,
		&i.CreatedAt,
	)
	return i, err
}

const setUserEmail = `-- name: SetUserEmail :one
UPDATE app_user SET email = $2 WHERE id = $1 RETURNING id, home_tenant_id, idp_issuer, idp_subject, email, created_at
`

type SetUserEmailParams struct {
	ID    string
	Email *string
}

// Only ever called with an email read from a VALIDATED ID token. An access
// token minted for an API resource carries no identity claims, so the value has
// to come from a signed assertion rather than from a request body.
func (q *Queries) SetUserEmail(ctx context.Context, arg SetUserEmailParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, setUserEmail, arg.ID, arg.Email)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.HomeTenantID,
		&i.IdpIssuer,
		&i.IdpSubject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const setWarmHold = `-- name: SetWarmHold :exec
UPDATE workspace SET warm_hold_until = $3 WHERE id = $1 AND tenant_id = $2
`

type SetWarmHoldParams struct {
	ID            string
	TenantID      string
	WarmHoldUntil *time.Time
}

// The warm-hold deadline, set when the last session in a workspace stops and
// cleared when one appears again. NULL means no hold is running.
//
// Deliberately NOT touching generation. An idle or warm-hold stop is a stop,
// not a placement: advancing the generation would invalidate the credential of
// a task that is alive and about to reconnect, and the ECS driver would then
// adopt that same still-running task and hand back its ARN -- leaving a task
// that can never authenticate again (internal/creds/creds.go).
func (q *Queries) SetWarmHold(ctx context.Context, arg SetWarmHoldParams) error {
	_, err := q.db.Exec(ctx, setWarmHold, arg.ID, arg.TenantID, arg.WarmHoldUntil)
	return err
}

const setWorkspaceAccessScope = `-- name: SetWorkspaceAccessScope :one
UPDATE workspace SET access_scope = $3 WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, owner_user_id, access_scope, next_uid, generation, task_ref, status, last_error, idle_timeout_secs, warm_hold_secs, warm_hold_until, snapshot_id, idle_pinned_since, admission_policy, max_sessions, min_free_memory_pct, created_at
`

type SetWorkspaceAccessScopeParams struct {
	ID          string
	TenantID    string
	AccessScope string
}

// Unlike a rename, this is safe while a task is live: nothing outside the
// database is keyed on the access scope, so widening or narrowing it changes
// who may ask for a session and nothing else. Sessions already running are not
// evicted -- see handleSetAccessScope.
func (q *Queries) SetWorkspaceAccessScope(ctx context.Context, arg SetWorkspaceAccessScopeParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, setWorkspaceAccessScope, arg.ID, arg.TenantID, arg.AccessScope)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OwnerUserID,
		&i.AccessScope,
		&i.NextUid,
		&i.Generation,
		&i.TaskRef,
		&i.Status,
		&i.LastError,
		&i.IdleTimeoutSecs,
		&i.WarmHoldSecs,
		&i.WarmHoldUntil,
		&i.SnapshotID,
		&i.IdlePinnedSince,
		&i.AdmissionPolicy,
		&i.MaxSessions,
		&i.MinFreeMemoryPct,
		&i.CreatedAt,
	)
	return i, err
}

const setWorkspacePolicy = `-- name: SetWorkspacePolicy :one
UPDATE workspace SET
    idle_timeout_secs   = $3,
    warm_hold_secs      = $4,
    admission_policy    = $5,
    max_sessions        = $6,
    min_free_memory_pct = $7
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, owner_user_id, access_scope, next_uid, generation, task_ref, status, last_error, idle_timeout_secs, warm_hold_secs, warm_hold_until, snapshot_id, idle_pinned_since, admission_policy, max_sessions, min_free_memory_pct, created_at
`

type SetWorkspacePolicyParams struct {
	ID               string
	TenantID         string
	IdleTimeoutSecs  int32
	WarmHoldSecs     int32
	AdmissionPolicy  string
	MaxSessions      int32
	MinFreeMemoryPct int32
}

// Section 2.4's lifecycle policy, all of it in one statement so a PATCH cannot
// half-apply.
func (q *Queries) SetWorkspacePolicy(ctx context.Context, arg SetWorkspacePolicyParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, setWorkspacePolicy,
		arg.ID,
		arg.TenantID,
		arg.IdleTimeoutSecs,
		arg.WarmHoldSecs,
		arg.AdmissionPolicy,
		arg.MaxSessions,
		arg.MinFreeMemoryPct,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OwnerUserID,
		&i.AccessScope,
		&i.NextUid,
		&i.Generation,
		&i.TaskRef,
		&i.Status,
		&i.LastError,
		&i.IdleTimeoutSecs,
		&i.WarmHoldSecs,
		&i.WarmHoldUntil,
		&i.SnapshotID,
		&i.IdlePinnedSince,
		&i.AdmissionPolicy,
		&i.MaxSessions,
		&i.MinFreeMemoryPct,
		&i.CreatedAt,
	)
	return i, err
}

const setWorkspaceSnapshot = `-- name: SetWorkspaceSnapshot :one
UPDATE workspace SET snapshot_id = $3 WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, owner_user_id, access_scope, next_uid, generation, task_ref, status, last_error, idle_timeout_secs, warm_hold_secs, warm_hold_until, snapshot_id, idle_pinned_since, admission_policy, max_sessions, min_free_memory_pct, created_at
`

type SetWorkspaceSnapshotParams struct {
	ID         string
	TenantID   string
	SnapshotID *string
}

// The workspace's disk between tasks (section 9 item 0).
//
// Two statements rather than one UPDATE, and the split is the whole design.
// ECS cannot re-attach a volume, so this column is the only thing connecting a
// stopped workspace to its filesystem: it is written when a snapshot COMPLETES,
// and the snapshot it replaces is deleted only after that write lands. A crash
// between them leaks a snapshot and costs money. The other order loses every
// member's home, which is not a cost, it is the product failing.
//
// Returns the row so the caller learns which snapshot it just displaced,
// without a second read that could observe a different one.
func (q *Queries) SetWorkspaceSnapshot(ctx context.Context, arg SetWorkspaceSnapshotParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, setWorkspaceSnapshot, arg.ID, arg.TenantID, arg.SnapshotID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OwnerUserID,
		&i.AccessScope,
		&i.NextUid,
		&i.Generation,
		&i.TaskRef,
		&i.Status,
		&i.LastError,
		&i.IdleTimeoutSecs,
		&i.WarmHoldSecs,
		&i.WarmHoldUntil,
		&i.SnapshotID,
		&i.IdlePinnedSince,
		&i.AdmissionPolicy,
		&i.MaxSessions,
		&i.MinFreeMemoryPct,
		&i.CreatedAt,
	)
	return i, err
}

const setWorkspaceStatus = `-- name: SetWorkspaceStatus :exec
UPDATE workspace SET status = $3, task_ref = $4, last_error = NULL
WHERE id = $1 AND tenant_id = $2
`

type SetWorkspaceStatusParams struct {
	ID       string
	TenantID string
	Status   string
	TaskRef  *string
}

// Clearing last_error here is the whole of the rule that keeps it honest: a
// status write is what a placement ATTEMPT does, so anything the previous
// attempt recorded stops applying at that moment. Written as part of the same
// statement rather than as a second one, because the two orders are not equally
// wrong -- clearing after the status write leaves a window in which the row
// reads `starting` with the last failure still attached to it, and that is
// precisely the row a console is polling.
func (q *Queries) SetWorkspaceStatus(ctx context.Context, arg SetWorkspaceStatusParams) error {
	_, err := q.db.Exec(ctx, setWorkspaceStatus,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.TaskRef,
	)
	return err
}

const upsertOrgSettings = `-- name: UpsertOrgSettings :one
INSERT INTO org_settings (tenant_id, members_can_create_workspaces)
VALUES ($1, $2)
ON CONFLICT (tenant_id) DO UPDATE
    SET members_can_create_workspaces = excluded.members_can_create_workspaces,
        updated_at                    = now()
RETURNING tenant_id, members_can_create_workspaces, updated_at
`

type UpsertOrgSettingsParams struct {
	TenantID                   string
	MembersCanCreateWorkspaces bool
}

func (q *Queries) UpsertOrgSettings(ctx context.Context, arg UpsertOrgSettingsParams) (OrgSetting, error) {
	row := q.db.QueryRow(ctx, upsertOrgSettings, arg.TenantID, arg.MembersCanCreateWorkspaces)
	var i OrgSetting
	err := row.Scan(&i.TenantID, &i.MembersCanCreateWorkspaces, &i.UpdatedAt)
	return i, err
}
