// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package directorydb

import (
	"time"
)

type Cell struct {
	ID        string
	Region    string
	DsnSecret string
	CreatedAt time.Time
}

type Directory struct {
	IdpIssuer  string
	IdpSubject string
	TenantID   string
	CreatedAt  time.Time
}

type InviteCode struct {
	Code      string
	TenantID  string
	Role      string
	ExpiresAt *time.Time
	MaxUses   *int32
	Uses      int32
	CreatedAt time.Time
}

type Tenant struct {
	ID            string
	CellID        string
	Slug          string
	Name          string
	NameGenerated bool
	IsPersonal    bool
	Plan          string
	CreatedAt     time.Time
}
