// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package directorydb

import (
	"context"
	"time"
)

const bindPrincipal = `-- name: BindPrincipal :execrows
INSERT INTO directory (idp_issuer, idp_subject, tenant_id)
VALUES ($1, $2, $3)
ON CONFLICT (idp_issuer, idp_subject) DO NOTHING
`

type BindPrincipalParams struct {
	IdpIssuer  string
	IdpSubject string
	TenantID   string
}

// Bind a principal to their home organization.
//
// DO NOTHING rather than DO UPDATE: two concurrent first requests from the same
// new user must converge on ONE organization, and whichever lost the race has
// to adopt the winner's rather than overwrite it. The caller re-reads. The
// loser's freshly created tenant row is then orphaned and gets deleted, which
// is why this returns the row count rather than the row.
func (q *Queries) BindPrincipal(ctx context.Context, arg BindPrincipalParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindPrincipal, arg.IdpIssuer, arg.IdpSubject, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createInviteCode = `-- name: CreateInviteCode :one
INSERT INTO invite_code (code, tenant_id, role, expires_at, max_uses)
VALUES ($1, $2, $3, $4, $5)
RETURNING code, tenant_id, role, expires_at, max_uses, uses, created_at
`

type CreateInviteCodeParams struct {
	Code      string
	TenantID  string
	Role      string
	ExpiresAt *time.Time
	MaxUses   *int32
}

func (q *Queries) CreateInviteCode(ctx context.Context, arg CreateInviteCodeParams) (InviteCode, error) {
	row := q.db.QueryRow(ctx, createInviteCode,
		arg.Code,
		arg.TenantID,
		arg.Role,
		arg.ExpiresAt,
		arg.MaxUses,
	)
	var i InviteCode
	err := row.Scan(
		&i.Code,
		&i.TenantID,
		&i.Role,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenant (id, cell_id, slug, name, is_personal, plan)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, cell_id, slug, name, name_generated, is_personal, plan, created_at
`

type CreateTenantParams struct {
	ID         string
	CellID     string
	Slug       string
	Name       string
	IsPersonal bool
	Plan       string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.CellID,
		arg.Slug,
		arg.Name,
		arg.IsPersonal,
		arg.Plan,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.CellID,
		&i.Slug,
		&i.Name,
		&i.NameGenerated,
		&i.IsPersonal,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInviteCode = `-- name: DeleteInviteCode :exec
DELETE FROM invite_code WHERE code = $1
`

func (q *Queries) DeleteInviteCode(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, deleteInviteCode, code)
	return err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenant WHERE id = $1
`

// Only ever called to clean up after losing the race above, and only for a
// tenant this transaction just created and then failed to bind.
func (q *Queries) DeleteTenant(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const getCell = `-- name: GetCell :one
SELECT id, region, dsn_secret, created_at FROM cell WHERE id = $1
`

func (q *Queries) GetCell(ctx context.Context, id string) (Cell, error) {
	row := q.db.QueryRow(ctx, getCell, id)
	var i Cell
	err := row.Scan(
		&i.ID,
		&i.Region,
		&i.DsnSecret,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteCode = `-- name: GetInviteCode :one
SELECT code, tenant_id, role, expires_at, max_uses, uses, created_at FROM invite_code WHERE code = $1
`

func (q *Queries) GetInviteCode(ctx context.Context, code string) (InviteCode, error) {
	row := q.db.QueryRow(ctx, getInviteCode, code)
	var i InviteCode
	err := row.Scan(
		&i.Code,
		&i.TenantID,
		&i.Role,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
		&i.CreatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, cell_id, slug, name, name_generated, is_personal, plan, created_at FROM tenant WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.CellID,
		&i.Slug,
		&i.Name,
		&i.NameGenerated,
		&i.IsPersonal,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, cell_id, slug, name, name_generated, is_personal, plan, created_at FROM tenant WHERE slug = $1
`

// The {org} path segment resolves through here. A slug is what a user types, so
// this is on every org-scoped request.
func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.CellID,
		&i.Slug,
		&i.Name,
		&i.NameGenerated,
		&i.IsPersonal,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantsByIDs = `-- name: GetTenantsByIDs :many
SELECT id, cell_id, slug, name, name_generated, is_personal, plan, created_at FROM tenant WHERE id = ANY ($1::uuid[]) ORDER BY created_at
`

// Names for a set of ids. The organizations a user belongs to are known in the
// CELL (org_member) while their names live here, so the switcher is one query
// per tier rather than a join -- the two tiers are separate databases by
// design, and a join across them does not exist to be written.
func (q *Queries) GetTenantsByIDs(ctx context.Context, dollar_1 []string) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, getTenantsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.CellID,
			&i.Slug,
			&i.Name,
			&i.NameGenerated,
			&i.IsPersonal,
			&i.Plan,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCells = `-- name: ListCells :many
SELECT id, region, dsn_secret, created_at FROM cell ORDER BY id
`

func (q *Queries) ListCells(ctx context.Context) ([]Cell, error) {
	rows, err := q.db.Query(ctx, listCells)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cell{}
	for rows.Next() {
		var i Cell
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.DsnSecret,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPrincipal = `-- name: LookupPrincipal :one
SELECT t.id AS tenant_id, t.slug, t.name, t.cell_id, t.plan, c.dsn_secret, c.region
FROM directory d
         JOIN tenant t ON t.id = d.tenant_id
         JOIN cell c ON c.id = t.cell_id
WHERE d.idp_issuer = $1
  AND d.idp_subject = $2
`

type LookupPrincipalParams struct {
	IdpIssuer  string
	IdpSubject string
}

type LookupPrincipalRow struct {
	TenantID  string
	Slug      string
	Name      string
	CellID    string
	Plan      string
	DsnSecret string
	Region    string
}

// Resolve an authenticated principal to their HOME organization and the cell
// holding it.
//
// The two-step request path starts here: nothing tenant-scoped can be queried
// until this has answered, because the answer names the database to ask. It
// returns one organization, not all of them -- the rest are memberships, and
// memberships live in the cell this row points at.
func (q *Queries) LookupPrincipal(ctx context.Context, arg LookupPrincipalParams) (LookupPrincipalRow, error) {
	row := q.db.QueryRow(ctx, lookupPrincipal, arg.IdpIssuer, arg.IdpSubject)
	var i LookupPrincipalRow
	err := row.Scan(
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.CellID,
		&i.Plan,
		&i.DsnSecret,
		&i.Region,
	)
	return i, err
}

const nameTenant = `-- name: NameTenant :execrows
UPDATE tenant
SET name = $2, name_generated = false
WHERE id = $1
  AND name_generated
`

type NameTenantParams struct {
	ID   string
	Name string
}

// Naming an organization properly needs an email, and an access token minted
// for an API resource carries none -- it arrives later, with the ID token. So
// sign-up writes a placeholder and this replaces it, ONCE: name_generated is
// what keeps a later rename from being silently overwritten by a re-login.
func (q *Queries) NameTenant(ctx context.Context, arg NameTenantParams) (int64, error) {
	result, err := q.db.Exec(ctx, nameTenant, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const redeemInviteCode = `-- name: RedeemInviteCode :one
UPDATE invite_code
SET uses = uses + 1
WHERE code = $1
  AND (expires_at IS NULL OR expires_at > now())
  AND (max_uses IS NULL OR uses < max_uses)
RETURNING code, tenant_id, role, expires_at, max_uses, uses, created_at
`

// Redeem in one statement so the use count cannot be checked and then
// incremented by two callers at once. Zero rows back means expired, exhausted,
// or never existed -- all of which are "this code does not work", and the caller
// deliberately cannot tell them apart.
func (q *Queries) RedeemInviteCode(ctx context.Context, code string) (InviteCode, error) {
	row := q.db.QueryRow(ctx, redeemInviteCode, code)
	var i InviteCode
	err := row.Scan(
		&i.Code,
		&i.TenantID,
		&i.Role,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCell = `-- name: UpsertCell :one
INSERT INTO cell (id, region, dsn_secret)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET region = excluded.region, dsn_secret = excluded.dsn_secret
RETURNING id, region, dsn_secret, created_at
`

type UpsertCellParams struct {
	ID        string
	Region    string
	DsnSecret string
}

func (q *Queries) UpsertCell(ctx context.Context, arg UpsertCellParams) (Cell, error) {
	row := q.db.QueryRow(ctx, upsertCell, arg.ID, arg.Region, arg.DsnSecret)
	var i Cell
	err := row.Scan(
		&i.ID,
		&i.Region,
		&i.DsnSecret,
		&i.CreatedAt,
	)
	return i, err
}
