/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiAuthCallbackRouteImport } from './routes/api.auth.callback'
import { Route as ApiAuthSignInRouteImport } from './routes/api.auth.sign-in'
import { Route as ApiAuthSignOutRouteImport } from './routes/api.auth.sign-out'
import { Route as AuthenticatedOrgsOrgIndexRouteImport } from './routes/_authenticated/orgs.$org.index'
import { Route as AuthenticatedOrgsOrgNewWorkspaceRouteImport } from './routes/_authenticated/orgs.$org.new-workspace'
import { Route as AuthenticatedOrgsOrgSettingsRouteImport } from './routes/_authenticated/orgs.$org.settings'
import { Route as AuthenticatedOrgsOrgWorkspacesWidRouteImport } from './routes/_authenticated/orgs.$org.workspaces.$wid'
import { Route as AuthenticatedOrgsOrgWorkspacesWidIndexRouteImport } from './routes/_authenticated/orgs.$org.workspaces.$wid.index'
import { Route as AuthenticatedOrgsOrgWorkspacesWidFilesystemRouteImport } from './routes/_authenticated/orgs.$org.workspaces.$wid.filesystem'
import { Route as AuthenticatedOrgsOrgWorkspacesWidMembersRouteImport } from './routes/_authenticated/orgs.$org.workspaces.$wid.members'
import { Route as AuthenticatedOrgsOrgWorkspacesWidProcessesRouteImport } from './routes/_authenticated/orgs.$org.workspaces.$wid.processes'
import { Route as AuthenticatedOrgsOrgWorkspacesWidSessionsRouteImport } from './routes/_authenticated/orgs.$org.workspaces.$wid.sessions'
import { Route as AuthenticatedOrgsOrgWorkspacesWidSessionsSidRouteImport } from './routes/_authenticated/orgs.$org.workspaces.$wid_.sessions.$sid'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgsOrgIndexRoute =
  AuthenticatedOrgsOrgIndexRouteImport.update({
    id: '/orgs/$org/',
    path: '/orgs/$org/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsOrgNewWorkspaceRoute =
  AuthenticatedOrgsOrgNewWorkspaceRouteImport.update({
    id: '/orgs/$org/new-workspace',
    path: '/orgs/$org/new-workspace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsOrgSettingsRoute =
  AuthenticatedOrgsOrgSettingsRouteImport.update({
    id: '/orgs/$org/settings',
    path: '/orgs/$org/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsOrgWorkspacesWidRoute =
  AuthenticatedOrgsOrgWorkspacesWidRouteImport.update({
    id: '/orgs/$org/workspaces/$wid',
    path: '/orgs/$org/workspaces/$wid',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsOrgWorkspacesWidIndexRoute =
  AuthenticatedOrgsOrgWorkspacesWidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgsOrgWorkspacesWidRoute,
  } as any)
const AuthenticatedOrgsOrgWorkspacesWidFilesystemRoute =
  AuthenticatedOrgsOrgWorkspacesWidFilesystemRouteImport.update({
    id: '/filesystem',
    path: '/filesystem',
    getParentRoute: () => AuthenticatedOrgsOrgWorkspacesWidRoute,
  } as any)
const AuthenticatedOrgsOrgWorkspacesWidMembersRoute =
  AuthenticatedOrgsOrgWorkspacesWidMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedOrgsOrgWorkspacesWidRoute,
  } as any)
const AuthenticatedOrgsOrgWorkspacesWidProcessesRoute =
  AuthenticatedOrgsOrgWorkspacesWidProcessesRouteImport.update({
    id: '/processes',
    path: '/processes',
    getParentRoute: () => AuthenticatedOrgsOrgWorkspacesWidRoute,
  } as any)
const AuthenticatedOrgsOrgWorkspacesWidSessionsRoute =
  AuthenticatedOrgsOrgWorkspacesWidSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedOrgsOrgWorkspacesWidRoute,
  } as any)
const AuthenticatedOrgsOrgWorkspacesWidSessionsSidRoute =
  AuthenticatedOrgsOrgWorkspacesWidSessionsSidRouteImport.update({
    id: '/orgs/$org/workspaces/$wid_/sessions/$sid',
    path: '/orgs/$org/workspaces/$wid/sessions/$sid',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/orgs/$org/new-workspace': typeof AuthenticatedOrgsOrgNewWorkspaceRoute
  '/orgs/$org/settings': typeof AuthenticatedOrgsOrgSettingsRoute
  '/orgs/$org/': typeof AuthenticatedOrgsOrgIndexRoute
  '/orgs/$org/workspaces/$wid': typeof AuthenticatedOrgsOrgWorkspacesWidRouteWithChildren
  '/orgs/$org/workspaces/$wid/filesystem': typeof AuthenticatedOrgsOrgWorkspacesWidFilesystemRoute
  '/orgs/$org/workspaces/$wid/members': typeof AuthenticatedOrgsOrgWorkspacesWidMembersRoute
  '/orgs/$org/workspaces/$wid/processes': typeof AuthenticatedOrgsOrgWorkspacesWidProcessesRoute
  '/orgs/$org/workspaces/$wid/sessions': typeof AuthenticatedOrgsOrgWorkspacesWidSessionsRoute
  '/orgs/$org/workspaces/$wid/': typeof AuthenticatedOrgsOrgWorkspacesWidIndexRoute
  '/orgs/$org/workspaces/$wid/sessions/$sid': typeof AuthenticatedOrgsOrgWorkspacesWidSessionsSidRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/orgs/$org/new-workspace': typeof AuthenticatedOrgsOrgNewWorkspaceRoute
  '/orgs/$org/settings': typeof AuthenticatedOrgsOrgSettingsRoute
  '/orgs/$org': typeof AuthenticatedOrgsOrgIndexRoute
  '/orgs/$org/workspaces/$wid/filesystem': typeof AuthenticatedOrgsOrgWorkspacesWidFilesystemRoute
  '/orgs/$org/workspaces/$wid/members': typeof AuthenticatedOrgsOrgWorkspacesWidMembersRoute
  '/orgs/$org/workspaces/$wid/processes': typeof AuthenticatedOrgsOrgWorkspacesWidProcessesRoute
  '/orgs/$org/workspaces/$wid/sessions': typeof AuthenticatedOrgsOrgWorkspacesWidSessionsRoute
  '/orgs/$org/workspaces/$wid': typeof AuthenticatedOrgsOrgWorkspacesWidIndexRoute
  '/orgs/$org/workspaces/$wid/sessions/$sid': typeof AuthenticatedOrgsOrgWorkspacesWidSessionsSidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/_authenticated/orgs/$org/new-workspace': typeof AuthenticatedOrgsOrgNewWorkspaceRoute
  '/_authenticated/orgs/$org/settings': typeof AuthenticatedOrgsOrgSettingsRoute
  '/_authenticated/orgs/$org/': typeof AuthenticatedOrgsOrgIndexRoute
  '/_authenticated/orgs/$org/workspaces/$wid': typeof AuthenticatedOrgsOrgWorkspacesWidRouteWithChildren
  '/_authenticated/orgs/$org/workspaces/$wid/filesystem': typeof AuthenticatedOrgsOrgWorkspacesWidFilesystemRoute
  '/_authenticated/orgs/$org/workspaces/$wid/members': typeof AuthenticatedOrgsOrgWorkspacesWidMembersRoute
  '/_authenticated/orgs/$org/workspaces/$wid/processes': typeof AuthenticatedOrgsOrgWorkspacesWidProcessesRoute
  '/_authenticated/orgs/$org/workspaces/$wid/sessions': typeof AuthenticatedOrgsOrgWorkspacesWidSessionsRoute
  '/_authenticated/orgs/$org/workspaces/$wid/': typeof AuthenticatedOrgsOrgWorkspacesWidIndexRoute
  '/_authenticated/orgs/$org/workspaces/$wid_/sessions/$sid': typeof AuthenticatedOrgsOrgWorkspacesWidSessionsSidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/orgs/$org/new-workspace'
    | '/orgs/$org/settings'
    | '/orgs/$org/'
    | '/orgs/$org/workspaces/$wid'
    | '/orgs/$org/workspaces/$wid/filesystem'
    | '/orgs/$org/workspaces/$wid/members'
    | '/orgs/$org/workspaces/$wid/processes'
    | '/orgs/$org/workspaces/$wid/sessions'
    | '/orgs/$org/workspaces/$wid/'
    | '/orgs/$org/workspaces/$wid/sessions/$sid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/orgs/$org/new-workspace'
    | '/orgs/$org/settings'
    | '/orgs/$org'
    | '/orgs/$org/workspaces/$wid/filesystem'
    | '/orgs/$org/workspaces/$wid/members'
    | '/orgs/$org/workspaces/$wid/processes'
    | '/orgs/$org/workspaces/$wid/sessions'
    | '/orgs/$org/workspaces/$wid'
    | '/orgs/$org/workspaces/$wid/sessions/$sid'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/_authenticated/orgs/$org/new-workspace'
    | '/_authenticated/orgs/$org/settings'
    | '/_authenticated/orgs/$org/'
    | '/_authenticated/orgs/$org/workspaces/$wid'
    | '/_authenticated/orgs/$org/workspaces/$wid/filesystem'
    | '/_authenticated/orgs/$org/workspaces/$wid/members'
    | '/_authenticated/orgs/$org/workspaces/$wid/processes'
    | '/_authenticated/orgs/$org/workspaces/$wid/sessions'
    | '/_authenticated/orgs/$org/workspaces/$wid/'
    | '/_authenticated/orgs/$org/workspaces/$wid_/sessions/$sid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orgs/$org/': {
      id: '/_authenticated/orgs/$org/'
      path: '/orgs/$org'
      fullPath: '/orgs/$org/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$org/new-workspace': {
      id: '/_authenticated/orgs/$org/new-workspace'
      path: '/orgs/$org/new-workspace'
      fullPath: '/orgs/$org/new-workspace'
      preLoaderRoute: typeof AuthenticatedOrgsOrgNewWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$org/settings': {
      id: '/_authenticated/orgs/$org/settings'
      path: '/orgs/$org/settings'
      fullPath: '/orgs/$org/settings'
      preLoaderRoute: typeof AuthenticatedOrgsOrgSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$org/workspaces/$wid': {
      id: '/_authenticated/orgs/$org/workspaces/$wid'
      path: '/orgs/$org/workspaces/$wid'
      fullPath: '/orgs/$org/workspaces/$wid'
      preLoaderRoute: typeof AuthenticatedOrgsOrgWorkspacesWidRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$org/workspaces/$wid/': {
      id: '/_authenticated/orgs/$org/workspaces/$wid/'
      path: '/'
      fullPath: '/orgs/$org/workspaces/$wid/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgWorkspacesWidIndexRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgWorkspacesWidRoute
    }
    '/_authenticated/orgs/$org/workspaces/$wid/filesystem': {
      id: '/_authenticated/orgs/$org/workspaces/$wid/filesystem'
      path: '/filesystem'
      fullPath: '/orgs/$org/workspaces/$wid/filesystem'
      preLoaderRoute: typeof AuthenticatedOrgsOrgWorkspacesWidFilesystemRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgWorkspacesWidRoute
    }
    '/_authenticated/orgs/$org/workspaces/$wid/members': {
      id: '/_authenticated/orgs/$org/workspaces/$wid/members'
      path: '/members'
      fullPath: '/orgs/$org/workspaces/$wid/members'
      preLoaderRoute: typeof AuthenticatedOrgsOrgWorkspacesWidMembersRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgWorkspacesWidRoute
    }
    '/_authenticated/orgs/$org/workspaces/$wid/processes': {
      id: '/_authenticated/orgs/$org/workspaces/$wid/processes'
      path: '/processes'
      fullPath: '/orgs/$org/workspaces/$wid/processes'
      preLoaderRoute: typeof AuthenticatedOrgsOrgWorkspacesWidProcessesRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgWorkspacesWidRoute
    }
    '/_authenticated/orgs/$org/workspaces/$wid/sessions': {
      id: '/_authenticated/orgs/$org/workspaces/$wid/sessions'
      path: '/sessions'
      fullPath: '/orgs/$org/workspaces/$wid/sessions'
      preLoaderRoute: typeof AuthenticatedOrgsOrgWorkspacesWidSessionsRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgWorkspacesWidRoute
    }
    '/_authenticated/orgs/$org/workspaces/$wid_/sessions/$sid': {
      id: '/_authenticated/orgs/$org/workspaces/$wid_/sessions/$sid'
      path: '/orgs/$org/workspaces/$wid/sessions/$sid'
      fullPath: '/orgs/$org/workspaces/$wid/sessions/$sid'
      preLoaderRoute: typeof AuthenticatedOrgsOrgWorkspacesWidSessionsSidRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedOrgsOrgWorkspacesWidRouteChildren {
  AuthenticatedOrgsOrgWorkspacesWidFilesystemRoute: typeof AuthenticatedOrgsOrgWorkspacesWidFilesystemRoute
  AuthenticatedOrgsOrgWorkspacesWidMembersRoute: typeof AuthenticatedOrgsOrgWorkspacesWidMembersRoute
  AuthenticatedOrgsOrgWorkspacesWidProcessesRoute: typeof AuthenticatedOrgsOrgWorkspacesWidProcessesRoute
  AuthenticatedOrgsOrgWorkspacesWidSessionsRoute: typeof AuthenticatedOrgsOrgWorkspacesWidSessionsRoute
  AuthenticatedOrgsOrgWorkspacesWidIndexRoute: typeof AuthenticatedOrgsOrgWorkspacesWidIndexRoute
}

const AuthenticatedOrgsOrgWorkspacesWidRouteChildren: AuthenticatedOrgsOrgWorkspacesWidRouteChildren =
  {
    AuthenticatedOrgsOrgWorkspacesWidFilesystemRoute:
      AuthenticatedOrgsOrgWorkspacesWidFilesystemRoute,
    AuthenticatedOrgsOrgWorkspacesWidMembersRoute:
      AuthenticatedOrgsOrgWorkspacesWidMembersRoute,
    AuthenticatedOrgsOrgWorkspacesWidProcessesRoute:
      AuthenticatedOrgsOrgWorkspacesWidProcessesRoute,
    AuthenticatedOrgsOrgWorkspacesWidSessionsRoute:
      AuthenticatedOrgsOrgWorkspacesWidSessionsRoute,
    AuthenticatedOrgsOrgWorkspacesWidIndexRoute:
      AuthenticatedOrgsOrgWorkspacesWidIndexRoute,
  }

const AuthenticatedOrgsOrgWorkspacesWidRouteWithChildren =
  AuthenticatedOrgsOrgWorkspacesWidRoute._addFileChildren(
    AuthenticatedOrgsOrgWorkspacesWidRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOrgsOrgNewWorkspaceRoute: typeof AuthenticatedOrgsOrgNewWorkspaceRoute
  AuthenticatedOrgsOrgSettingsRoute: typeof AuthenticatedOrgsOrgSettingsRoute
  AuthenticatedOrgsOrgIndexRoute: typeof AuthenticatedOrgsOrgIndexRoute
  AuthenticatedOrgsOrgWorkspacesWidRoute: typeof AuthenticatedOrgsOrgWorkspacesWidRouteWithChildren
  AuthenticatedOrgsOrgWorkspacesWidSessionsSidRoute: typeof AuthenticatedOrgsOrgWorkspacesWidSessionsSidRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOrgsOrgNewWorkspaceRoute: AuthenticatedOrgsOrgNewWorkspaceRoute,
  AuthenticatedOrgsOrgSettingsRoute: AuthenticatedOrgsOrgSettingsRoute,
  AuthenticatedOrgsOrgIndexRoute: AuthenticatedOrgsOrgIndexRoute,
  AuthenticatedOrgsOrgWorkspacesWidRoute:
    AuthenticatedOrgsOrgWorkspacesWidRouteWithChildren,
  AuthenticatedOrgsOrgWorkspacesWidSessionsSidRoute:
    AuthenticatedOrgsOrgWorkspacesWidSessionsSidRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
