/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesWidRouteImport } from './routes/workspaces.$wid'
import { Route as WorkspacesWidSessionsSidRouteImport } from './routes/workspaces.$wid_.sessions.$sid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWidRoute = WorkspacesWidRouteImport.update({
  id: '/workspaces/$wid',
  path: '/workspaces/$wid',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWidSessionsSidRoute =
  WorkspacesWidSessionsSidRouteImport.update({
    id: '/workspaces/$wid_/sessions/$sid',
    path: '/workspaces/$wid/sessions/$sid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspaces/$wid': typeof WorkspacesWidRoute
  '/workspaces/$wid/sessions/$sid': typeof WorkspacesWidSessionsSidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspaces/$wid': typeof WorkspacesWidRoute
  '/workspaces/$wid/sessions/$sid': typeof WorkspacesWidSessionsSidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspaces/$wid': typeof WorkspacesWidRoute
  '/workspaces/$wid_/sessions/$sid': typeof WorkspacesWidSessionsSidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workspaces/$wid' | '/workspaces/$wid/sessions/$sid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workspaces/$wid' | '/workspaces/$wid/sessions/$sid'
  id: '__root__' | '/' | '/workspaces/$wid' | '/workspaces/$wid_/sessions/$sid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspacesWidRoute: typeof WorkspacesWidRoute
  WorkspacesWidSessionsSidRoute: typeof WorkspacesWidSessionsSidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$wid': {
      id: '/workspaces/$wid'
      path: '/workspaces/$wid'
      fullPath: '/workspaces/$wid'
      preLoaderRoute: typeof WorkspacesWidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$wid_/sessions/$sid': {
      id: '/workspaces/$wid_/sessions/$sid'
      path: '/workspaces/$wid/sessions/$sid'
      fullPath: '/workspaces/$wid/sessions/$sid'
      preLoaderRoute: typeof WorkspacesWidSessionsSidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspacesWidRoute: WorkspacesWidRoute,
  WorkspacesWidSessionsSidRoute: WorkspacesWidSessionsSidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
